services:
  gateway-service:
    build: .
    image: gateway-service:latest
    container_name: gateway-service
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SERVER_PORT=${SERVER_PORT}
      - EUREKA_URL=${EUREKA_URL}
      - KEYCLOAK_ISSUER_URI=${KEYCLOAK_ISSUER_URI}
    ports:
      - "8888:8888"
    networks:
      - microservices-net

networks:
  microservices-net:
    external: true